# Generated by Django 5.0.9 on 2026-09-14 21:57

import alunos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, validators=[alunos.models.validar_cpf_formato])),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('disciplina', models.CharField(blank=True, max_length=100)),
                ('serie_nivel', models.CharField(blank=True, max_length=100)),
                ('escola', models.CharField(blank=True, max_length=150)),
                ('observacoes', models.TextField(blank=True)),
                ('responsavel_nome', models.CharField(blank=True, max_length=150)),
                ('responsavel_telefone', models.CharField(blank=True, max_length=20)),
                ('responsavel_email', models.EmailField(blank=True, max_length=254)),
                ('responsavel_parentesco', models.CharField(blank=True, max_length=50)),
                ('valor_hora', models.DecimalField(blank=True, decimal_places=2, help_text='Se vazio, usa o valor-hora padrão do professor.', max_digits=8, null=True)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['professor', 'nome'], name='idx_aluno_professor_nome'), models.Index(fields=['professor', 'situacao'], name='idx_aluno_professor_situacao')],
            },
        ),
        migrations.AddConstraint(
            model_name='aluno',
            constraint=models.UniqueConstraint(fields=('professor', 'cpf'), name='uniq_cpf_por_professor'),
        ),
    ]
