# Generated by Django 5.0.9 on 2026-09-17 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aluno',
            constraint=models.CheckConstraint(check=models.Q(('saldo_devedor__gte', 0)), name='aluno_saldo_devedor_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='aluno',
            constraint=models.CheckConstraint(check=models.Q(('valor_hora__isnull', True), ('valor_hora__gt', 0), _connector='OR'), name='aluno_valor_hora_nulo_ou_positivo'),
        ),
    ]
