# Generated by Django 5.0.9 on 2026-09-14 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('duracao_minutos', models.PositiveIntegerField(default=60)),
                ('modalidade', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online')], default='PRESENCIAL', max_length=12)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('FALTA', 'Falta')], default='AGENDADA', max_length=10)),
                ('conteudo_trabalhado', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('tipo_falta', models.CharField(blank=True, help_text='JUSTIFICADA ou NAO_JUSTIFICADA, quando status = FALTA.', max_length=20)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=255)),
                ('data_registro', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='alunos.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_hora_inicio'],
                'indexes': [models.Index(fields=['professor', 'data_hora_inicio'], name='idx_aula_professor_data'), models.Index(fields=['aluno', 'status'], name='idx_aula_aluno_status')],
            },
        ),
    ]
