# Generated by Django 5.0.9 on 2026-09-17 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('alunos', '0002_aluno_aluno_saldo_devedor_nao_negativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aula',
            constraint=models.CheckConstraint(check=models.Q(('duracao_minutos__gt', 0)), name='aula_duracao_positiva'),
        ),
    ]
