# Generated by Django 5.0.9 on 2026-09-14 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_hora_padrao', models.DecimalField(decimal_places=2, default=0, help_text='Valor padrão da hora-aula, usado quando o aluno não tem valor próprio definido.', max_digits=8)),
                ('antecedencia_minima_cancelamento_horas', models.PositiveIntegerField(default=24, help_text='Antecedência mínima (em horas) para cancelamento sem cobrança.')),
                ('dia_vencimento_padrao', models.PositiveSmallIntegerField(default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
