# Generated by Django 5.0.9 on 2026-09-14 21:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Use o primeiro dia do mês de referência.')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='alunos.aluno')),
            ],
            options={
                'ordering': ['-competencia'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField(default=django.utils.timezone.localdate)),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão'), ('TRANSFERENCIA', 'Transferência'), ('OUTRO', 'Outro')], max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('mensalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.mensalidade')),
            ],
            options={
                'ordering': ['-data_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='mensalidade',
            index=models.Index(fields=['aluno', 'status'], name='idx_mensalidade_aluno_status'),
        ),
        migrations.AddIndex(
            model_name='mensalidade',
            index=models.Index(fields=['data_vencimento', 'status'], name='idx_mensalidade_venc_status'),
        ),
    ]
