# Generated by Django 5.0.9 on 2026-09-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_aluno_saldo_devedor_nao_negativo_and_more'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mensalidade',
            constraint=models.CheckConstraint(check=models.Q(('valor_total__gt', 0)), name='mensalidade_valor_total_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.CheckConstraint(check=models.Q(('valor_pago__gt', 0)), name='pagamento_valor_pago_positivo'),
        ),
    ]
